version: "3.9"

services:
  backend:
    build:
      context: ../p2p-chat-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: ../p2p-chat-web
    ports:
      - "8000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped